export const claims = {
  Pricing_Table: [
    {
      Patient_id: "ABCDEG",
      Claim_id: "C0001",
      Cost_of_the_claim: "$500",
      Patient_pay: "$500",
      Client_pay: "0",
    },
    {
      Patient_id: "ABCDEG",
      Claim_id: "C0002",
      Cost_of_the_claim: "$500",
      Patient_pay: "$60",
      Client_pay: "$460",
    },
    {
      Patient_id: "ABCDEG",
      Claim_id: "C0003",
      Cost_of_the_claim: "$1000",
      Patient_pay: "$300",
      Client_pay: "$700",
    },
  ],
  Accumulator_Table: [
    {
      Patient_id: "ABCDEG",
      Claim_id: "C0001",
      Accum_type: "01",
      Frame_id: "1111",
      starting_amount: "$0",
      Approved_amount: "$500",
      Applied_amount: "$500",
      remaining_amount: "$300",
    },
    {
      Patient_id: "ABCDEG",
      Claim_id: "C0001",
      Accum_type: "03",
      Frame_id: "1111",
      starting_amount: "$500",
      Approved_amount: "$0",
      Applied_amount: "$0",
      remaining_amount: "$1000",
    },
    {
      Patient_id: "ABCDEG",
      Claim_id: "C0002",
      Accum_type: "01",
      Frame_id: "1111",
      starting_amount: "$500",
      Approved_amount: "$500",
      Applied_amount: "$300",
      remaining_amount: "$0",
    },
    {
      Patient_id: "ABCDEG",
      Claim_id: "C0002",
      Accum_type: "03",
      Frame_id: "1111",
      starting_amount: "$0",
      Approved_amount: "$200",
      Applied_amount: "$60",
      remaining_amount: "$940",
    },
    {
      Patient_id: "ABCDEG",
      Claim_id: "C0003",
      Accum_type: "01",
      Frame_id: "1111",
      starting_amount: "$800",
      Approved_amount: "$1000",
      Applied_amount: "$0",
      remaining_amount: "$0",
    },
    {
      Patient_id: "ABCDEG",
      Claim_id: "C0003",
      Accum_type: "03",
      Frame_id: "1111",
      starting_amount: "$60",
      Approved_amount: "$1000",
      Applied_amount: "$300",
      remaining_amount: "$640",
    },
  ],
}
